---
title: "Week1"
author: "Ivy Fernandes"
date: "5/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1.2 challenge #1
```{r}
#Code Challenge: Implement PatternCount (reproduced below).
#     Input: Strings Text and Pattern.
#     Output: Count(Text, Pattern).
data<-read.delim("data/dataset_2_7.txt",header=FALSE, sep="\n") %>% unlist
#want to do header = FALSE or else the first string will become a header in the table being created using the read.delim function. 
class(data)
seq<-data[1]
pattern<-data[2]
View(seq)
View(pattern)
#install.packages("stringr")
library("stringr")
# count the number of times the pattern appears in sequence
#another package that seems to serve the same function is gregexpr
#utilizing the str_count function that is within the stringr package downloaded
count<-str_count(seq,pattern)
count
#this does not count overlapping regions
#online it says to use look-ahead to overcome this
  #add ?... where ... is your pattern
count_all<-str_count(seq,pattern)
count_all<-str_count(seq, str_c("(?=",pattern,")"))
count_all
```

## 1.2 challenge #2
```{r}
# Code Challenge: Solve the Frequent Words Problem.
# Input: A string Text and an integer k.
# Output: All most frequent k-mers in Text.
# This will be my first time creating my own function in R. First I want to define this function called "frequentwords" and specify the inputs
#text will be the entire string of text that will be analyzed for patterns while k is the number of nucliotides within the substring of text
# we want this function to identify the patterns that occur the most, so we need it to be able to count how frequently these patterns appear
data2<-read.delim("data/dataset_2_10.txt",header=FALSE, sep="\n")
data2<-unlist(data2)
text<-data2[1]
  k<-data2[2]
  k<-as.numeric(k)
  frequentpatterns<- c()
#want to be able to identify these patterns, so they will be listed into this data frame that will start out as empty and be populated as the text is read
#we want the frequent words function to move along the "text" from the starting point (i) to the ending point
start<-1
end<-nchar(text)-k
maxcount<-0
for (i in start:end){
  pattern<- substr(text,i,i+k-1)
  #print(pattern) 
  count<-str_count(text, str_c("(?=",pattern,")"))
  #print(count)
  if (count>maxcount){
    maxcount<-count
  }
}
print(maxcount)

# Now that we have identified the maximum amount of times a string, or various strings, appear, we want to identify what those strings are

for (i in start:end){
  pattern<- substr(text,i,i+k-1)
  #print(pattern) 
  count<-str_count(text, str_c("(?=",pattern,")"))
  #print(count)
  if (count== maxcount){
  frequentpatterns<- c(frequentpatterns,pattern)
  }
}

#removeduplicates
frequentpatterns<-unique(frequentpatterns)

print(frequentpatterns)
```
## 1.3 challenge #3
```{r}
#Reverse Complement Problem: Find the reverse complement of a DNA string.
#Input: A DNA string Pattern.
#Output: Pattern*, the reverse complement of Pattern.
# If the original pattern has an A we want to return a T, if the original pattern as a G we want to return a C and vice versa. Additionally, we want the returned pattern (the compliment) to read in the 5' to 3' direction. So if we read the template pattern as P1 to Pn, we want the compliment to read from Pn* to P1*

data3<-read.delim("data/dataset_3_2.txt",header=FALSE, sep="\n")
data3<-unlist(data3)
text<-data3[1]
print(text)
compliment<-c()
#compliment will be the direct compliment, so it will be read in the 3' to 5' direction. Later I will try to print it backwards so that it is the recerse compliment reading in the 5' to 3' direction
#Utilize == as a mediator to turn 1) A to T, 2) T to A, 3) G to C, and 4) C to G
start<-1
end<-nchar(text)
for (i in start:end){
  complimenti<- substr(text,i,i)
  #print(complimenti) 
  if (complimenti== "A"){
  compliment<- c(compliment,"T")
  }
  if (complimenti== "T"){
  compliment<- c(compliment,"A")
  }
  if (complimenti== "C"){
  compliment<- c(compliment,"G")
  }
  if (complimenti== "G"){
  compliment<- c(compliment,"C")
  }
}

#Now I want to get the reverse compliment, so I will utilize the rev function
revcompliment<-rev(compliment)
#print(revcompliment)
# I want this to read as a single string
revcompliment<-paste(revcompliment, sep="", collapse="") 
print(revcompliment)
```


## 1.3 Challenge #4
```{r}
#Code Challenge: Solve the Pattern Matching Problem.
# Input: Two strings, Pattern and Genome.
# Output: A collection of space-separated integers specifying all starting positions where Pattern appears as a substring of Genome.
# We want to return the index at which the pattern starts within the larger string

data4<-read.delim("data/dataset_3_5.txt",header=FALSE, sep="\n")
data4<-unlist(data4)
genome<-data4[2]
pattern<-data4[1]
k<-nchar(pattern)
start<-1
end<-nchar(genome)-nchar(pattern)
patternindex<- c()
for (i in start:end){
  subgenome<- substr(genome,i,i+k-1)
  if (subgenome == pattern){
    patternindex<-c(patternindex,i)
  }
}
# offset<-patternindex-1
patternindex <- paste(patternindex, collapse=" ")
# offset<-paste(offset, collapse=" ")
# print(offset)
print(patternindex)
```

